### ISSUE TITLE
Travelers want to connect with people who have also visited the same points of interest

### ISSUE THREAD

**Issue by RandomY-2** [RandomY-2/CS130#3]
## Epic
Travelers want to connect with people who have also visited the same points of interest. The app aims to foster a vibrant community of travelers

## User Stories
- [x] Users want to unlock a discussion board to connect with people who have also visited the same points of interest after their photos and locations have been verified (Backend: #15 )
- [x] In the discussion board, users want to be able to view and post messages with other users who've been verified for this point of interest  (Backend: #16 )
- [x] For each point of interest, users want to be able to see the aggregate rating given by other users and be able to give their own rating (Backend: #17 )
